<img align="left" src="img/ECE364-logo.png" width="300px" style="padding:30px;border:thin solid white;"> 

# Lecture 3 - Linear Algebra II
## ECE364 - Programming Methods for Machine Learning
### Nickvash Kani 












###### Slides based off prior lectures by Alex Schwing, Aigou Han, Farzas Kamalabadi, Corey Snyder. All mistakes are my own!

Things we'll cover in today's lecture:

- More matrix operations
- Solving systems of linear equations
- Introduction to matrix calculus


## More matrix operations
Here are more functions for matrix operations:
## Slice:
* Slicing means selecting the elements present in the tensor by using “:” slice operator. We can slice the elements by using the index of that particular element.
* Let’s create a 3D Tensor for demonstration. We can create a vector by using **torch.tensor()** function


In [3]:
# import torch module
import torch
  
# create an 3 D tensor with 8 elements each
a = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8],
                   [10, 11, 12, 13, 14, 15, 16, 17]],
                    
                  [[71, 72, 73, 74, 75, 76, 77, 78],
                   [81, 82, 83, 84, 85, 86, 87, 88]]])
  
# display actual  tensor
print(a)


tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8],
         [10, 11, 12, 13, 14, 15, 16, 17]],

        [[71, 72, 73, 74, 75, 76, 77, 78],
         [81, 82, 83, 84, 85, 86, 87, 88]]])


**Alertness Check:** What is the shape of this tensor? 

In [56]:
print(a.shape)

torch.Size([2, 2, 8])


**Alertness Check:** Some fun slicing problems:

In [65]:
a = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8],
                   [10, 11, 12, 13, 14, 15, 16, 17]],
                    
                  [[71, 72, 73, 74, 75, 76, 77, 78],
                   [81, 82, 83, 84, 85, 86, 87, 88]]])
  
# display actual  tensor
print(a)

print(a[ 0:1, 0:1, :8:2])
b = a[ 0, 0, :8:2]
print(b.shape)

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8],
         [10, 11, 12, 13, 14, 15, 16, 17]],

        [[71, 72, 73, 74, 75, 76, 77, 78],
         [81, 82, 83, 84, 85, 86, 87, 88]]])
tensor([[[1, 3, 5, 7]]])
torch.Size([4])


How do we get every other value in the first row displayed above?

In [3]:
# access  all the tensors of 1 
# dimension and get only 7 values 
# in that dimension
print(a[0:1, 0:1, :8:2])

tensor([[[1, 3, 5, 7]]])


In [5]:
a = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8],
                   [10, 11, 12, 13, 14, 15, 16, 17]],
                    
                  [[71, 72, 73, 74, 75, 76, 77, 78],
                   [81, 82, 83, 84, 85, 86, 87, 88]]])
  
# display actual  tensor
print(a)

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8],
         [10, 11, 12, 13, 14, 15, 16, 17]],

        [[71, 72, 73, 74, 75, 76, 77, 78],
         [81, 82, 83, 84, 85, 86, 87, 88]]])


What will the code below display (value and shape)? 

In [62]:
# access  all the tensors of all
# dimensions and get only 3 values 
# in each dimension
print(a[0:1, 0:2, :3])

tensor([[[ 1,  2,  3],
         [10, 11, 12]]])


In [9]:
a = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8],
                   [10, 11, 12, 13, 14, 15, 16, 17]],
                    
                  [[71, 72, 73, 74, 75, 76, 77, 78],
                   [81, 82, 83, 84, 85, 86, 87, 88]]])
  
# display actual  tensor
print(a)

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8],
         [10, 11, 12, 13, 14, 15, 16, 17]],

        [[71, 72, 73, 74, 75, 76, 77, 78],
         [81, 82, 83, 84, 85, 86, 87, 88]]])


What will the code below display (value and shape)?

In [64]:
# access 8 elements in 1 dimension
# on all tensors
print(a[0:2, 1, 0:8])
b = a[0:2, 1, 0:8]
print(b.shape)

tensor([[10, 11, 12, 13, 14, 15, 16, 17],
        [81, 82, 83, 84, 85, 86, 87, 88]])
torch.Size([2, 8])


## Broadcasting 

Quick diversion, what is the output of the following code: 

In [68]:
import torch

a = torch.arange(2).view(-1,1)
b = torch.arange(2).view(1,-1)

print(a)
print(b)

print(a+b)

tensor([[0],
        [1]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2]])


In [69]:
import numpy as np

a = np.array([0, 1])
b = np.array([[0], [1]])

print(a+b)

[[0 1]
 [1 2]]


While everyone is familiar with ```numpy```(```torch```) slicing, broadcasting it less used. So I thought it would be worthwhile to brush upon it quickly. 

When adding an array and a scaler, we know we want to add the element to every element in the array. 

In [70]:
import numpy as np

a = np.array([1,2,3,4])
b = a+1

print(b)

[2 3 4 5]


Another way to look at this is that the dimension of the scalar is being stretched: 

<img align="center" src="img/broadcasting_scalar_vec.png" width="1200px" style="padding:30px;border:thin solid white;"> 


Works with matrix to matrix operations too: 

In [17]:
import torch

a = torch.arange(12).view(4,3)
b = torch.arange(3).view(1,3)

print(a)
print(b)
print(a*b)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[0, 1, 2]])
tensor([[ 0,  1,  4],
        [ 0,  4, 10],
        [ 0,  7, 16],
        [ 0, 10, 22]])


<img align="center" src="img/broadcasting_matrix_matrix.png" width="600px" style="padding:30px;border:thin solid white;"> 


General broadcasting rule:

When operating two arrays, NumPy compares their shapes, element-wise from right to left and tries to find two dimensions that are:  
- equal
- one of them is size 1
Then it stretches those dimenisons to make the array match. 

Two arrays do not need to have to same number of dimenisons, but the resulting array will have the number of dimenisons equal to the input array with the greatest number of dimensions. 


What does the following code snippet produce: 

In [71]:
import torch

a = torch.tensor([[0,1,2,3], [4,5,6,7]])
b = torch.tensor([[0,1,2]])

print(a)
print(b)
print(a*b)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2]])


RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

Broadasting provides a useful way fo taking the outer-product of any set of arrays

In [76]:
import torch

# Define the size of each dimension
size = 10

# Create the 4D array with shape (10, 10, 10, 10)
# Generate indices from 0 to 9 in each dimension
a = torch.arange(size).view(-1, 1, 1, 1)  # Shape (10, 1, 1, 1)
b = torch.arange(size).view(1, -1, 1, 1)  # Shape (1, 10, 1, 1)
c = torch.arange(size).view(1, 1, -1, 1)  # Shape (1, 1, 10, 1)
d = torch.arange(size).view(1, 1, 1, -1)  # Shape (1, 1, 1, 10)

# Compute the 4D array where each index corresponds to the concatenation of a, b, c, d
z = a * 1000 + b * 100 + c * 10 + d

x = a+b
print(x.shape)
y = x+c
print(y.shape)
#Print the resulting 4D tensor
print(z)

torch.Size([10, 10, 1, 1])
torch.Size([10, 10, 10, 1])
tensor([[[[   0,    1,    2,  ...,    7,    8,    9],
          [  10,   11,   12,  ...,   17,   18,   19],
          [  20,   21,   22,  ...,   27,   28,   29],
          ...,
          [  70,   71,   72,  ...,   77,   78,   79],
          [  80,   81,   82,  ...,   87,   88,   89],
          [  90,   91,   92,  ...,   97,   98,   99]],

         [[ 100,  101,  102,  ...,  107,  108,  109],
          [ 110,  111,  112,  ...,  117,  118,  119],
          [ 120,  121,  122,  ...,  127,  128,  129],
          ...,
          [ 170,  171,  172,  ...,  177,  178,  179],
          [ 180,  181,  182,  ...,  187,  188,  189],
          [ 190,  191,  192,  ...,  197,  198,  199]],

         [[ 200,  201,  202,  ...,  207,  208,  209],
          [ 210,  211,  212,  ...,  217,  218,  219],
          [ 220,  221,  222,  ...,  227,  228,  229],
          ...,
          [ 270,  271,  272,  ...,  277,  278,  279],
          [ 280,  281,  282,  ..

## Linear equations

### What is a linear equation?
* Wikipedia defines a system of linear equations as:<br>

>In mathematics, a system of linear equations (or linear system) is a collection of two or more linear equations involving the same set of variables.<br>

## Representing Systems of Linear Equations using Matrices
* A system of linear equations can be represented in matrix form using a coefficient matrix, a variable matrix, and a constant matrix. <Br>
* **General form of a linear system:** A linear system has $n$ unknown and $m$ equations: <Br>
    $\begin{array}{c}
a_{11}x_{1}+a_{12}x_{2}+\ldots+a_{1n}x_{n}=b_{1}\\
a_{21}x_{1}+a_{22}x_{2}+\ldots+a_{2n}x_{n}=b_{2}\\
\vdots\\
a_{m1}x_{1}+a_{m2}x_{2}+\ldots+a_{mn}x_{n}=b_{m}
\end{array}$ <Br>
Where $x_1, x_2,..., x_n$ are the unknowns, $a_11, a_12, ..., a_mn$ are the coefficients of the system, and $b_1, b_2,..., b_m$ are the constant terms.
* **Vector equation:** One helpful view is that each unknown is a weight for a column vector in a linear combination
$x_{1}\left[\begin{array}{c}
a_{11}\\
a_{21}\\
\vdots\\
a_{m1}
\end{array}\right]+x_{2}\left[\begin{array}{c}
a_{12}\\
a_{22}\\
\vdots\\
a_{m2}
\end{array}\right]+\cdots+x_{n}\left[\begin{array}{c}
a_{1n}\\
a_{2n}\\
\vdots\\
a_{mn}
\end{array}\right]=\left[\begin{array}{c}
b_{1}\\
b_{2}\\
\vdots\\
b_{m}
\end{array}\right]$

## Representing Systems of Linear Equations using Matrices
* **Matrix equation:** The vector equation is equivalent to a matrix equation of the form. 

    $Ax=\left[\begin{matrix}a_{11} & a_{12} & \ldots & a_{1n}\\
a_{21} & a_{22} & \vdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{matrix}\right]\left[\begin{matrix}x_{1}\\
x_{2}\\
\vdots\\
x_{n}
\end{matrix}\right]=\left[\begin{matrix}a_{11}x_{1}+a_{12}x_{2}+\ldots+a_{1n}x_{n}\\
a_{21}x_{1}+a_{22}x_{2}+\ldots+a_{2n}x_{n}\\
\ldots\\
a_{m1}x_{1}+a_{m2}x_{2}+\ldots+a_{mn}x_{n}
\end{matrix}\right]=x_{1}\left[\begin{array}{c}
a_{11}\\
a_{21}\\
\vdots\\
a_{m1}
\end{array}\right]+x_{2}\left[\begin{array}{c}
a_{12}\\
a_{22}\\
\vdots\\
a_{m2}
\end{array}\right]+\cdots+x_{n}\left[\begin{array}{c}
a_{1n}\\
a_{2n}\\
\vdots\\
a_{mn}
\end{array}\right]=\left[\begin{matrix}b_{1}\\
b_{2}\\
\vdots\\
b_{n}
\end{matrix}\right]=B$ <br>

   Where  $A=\left[\begin{matrix}a_{11} & a_{12} & \ldots & a_{1n}\\
a_{21} & a_{22} & \vdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{matrix}\right],x=\left[\begin{matrix}x_{1}\\
x_{2}\\
\vdots\\
x_{n}
\end{matrix}\right],b=\left[\begin{matrix}b_{1}\\
b_{2}\\
\vdots\\
b_{n}
\end{matrix}\right]$

    Then, the linear equations can be written this way:<Br>
    $Ax=B$ <Br>
    to solve for the vector x, we must take the inverse of matrix A and the equation is written as follows:    <Br>
    $x=A^{-1}B$ <Br>   

## Solving linear equations using matrices 
* Let's start from an example:<br>
    $2x_1+x_2+x_3=4$<br>
    $x_1+3x_2+2x_3=5$<br>
    $x_1=6$<br>
    Now, we can formalize the problem with matrices: <Br>
    $A=\left[\begin{array}{ccc}
    2 & 1 & 1\\
    1 & 3 & 2\\
    1 & 0 & 0
    \end{array}\right],x=\left[\begin{array}{c}
    x_1\\
    x_2\\
    x_3
    \end{array}\right],B=\left[\begin{array}{c}
    4\\
    5\\
    6
    \end{array}\right]$ <Br>
    Then, the linear equations can be written this way: <Br>
    $Ax=B$ <Br>
    to solve for the vector x, we must take the inverse of matrix A and the equation is written as follows:    <Br>
    $x=A^{-1}B$ <Br>    

## Solving linear equations using matrices (continued) 
* Lets solve the example in previous slide:

Since, $x=A^{-1}B$

|First find $A^{-1}$ : | Then we need to multiply it by B | and get the following solution |
| ---- | ---- | ---- |
|$$ A^{-1}=\left[\begin{array}{ccc} 2 & 1 & 1\\ 1 & 3 & 2\\ 1 & 0 & 0 \end{array}\right]^{-1}  = \left[\begin{array}{ccc} 0 & 0 & 1\\ -2 & 1 & 3\\ 3 & -1 & -5 \end{array}\right] $$ | $$\left[\begin{array}{ccc} 0 & 0 & 1\\ -2 & 1 & 3\\ 3 & -1 & -5 \end{array}\right] \cdot \left[\begin{array}{ccc} 4 \\ 5 \\ 6 \end{array}\right] $$ |$$=\left[\begin{array}{ccc} 6 \\ 15 \\ -23 \end{array}\right]$$ | 

In [77]:
import torch

A = torch.tensor([[2,1,1], [1, 3, 2], [1, 0, 0]], dtype=float)
b = torch.tensor([4, 5, 6], dtype=float)

A_i = A.inverse()

print(A_i@b)

tensor([  6.0000,  15.0000, -23.0000], dtype=torch.float64)


Or we just use the builtin ```PyTorch``` function, ```linalg.solve``` that does this for us!

In [31]:
print(torch.linalg.solve(A,b))

tensor([  6.0000,  15.0000, -23.0000], dtype=torch.float64)


Why does ```linalg.solve``` if we can just say ```A.inverse() @ b```?

### Why `torch.linalg.solve` is Better than Taking the Inverse

1. **Numerical Stability:**
   - `torch.linalg.solve` uses specialized methods like LU decomposition or other direct solvers that are numerically stable. 
   - Computing the inverse explicitly can amplify errors in the matrix, especially for ill-conditioned matrices.

2. **Performance:**
   - Calculating the inverse of a matrix is an \( O(n^3) \) operation. After that, multiplying by \( B \) takes another \( O(n^2) \). 
   - In contrast, `torch.linalg.solve` directly computes the solution with optimized algorithms that avoid the costly inversion step.
   - It is generally faster because it uses efficient methods such as LU decomposition or other factorizations, which are faster than computing the inverse.

3. **Efficient Memory Use:**
   - `torch.linalg.solve` does not require storing the inverse of \( A \), which is a \( n \times n \) matrix.
   - This reduces memory consumption, especially for large matrices.

In [34]:
import torch
import time

# Set the size of the matrix A
n = 1000

# Generate a random square matrix A and a random vector B
A = torch.randn(n, n)
B = torch.randn(n)

# Ensure A is invertible by making it symmetric positive definite
A = A @ A.T + n * torch.eye(n)  # A * A^T + large scalar to make it invertible

# Method 1: Using torch.linalg.solve to solve A * x = B
start_time = time.time()
x_solve = torch.linalg.solve(A, B)
time_solve = time.time() - start_time

# Method 2: Inverse of A and multiply by B
start_time = time.time()
A_inv = torch.linalg.inv(A)  # Calculate the inverse of A
x_inv = A_inv @ B  # Multiply by B
time_inv = time.time() - start_time

# Check if both methods give the same result
print(f"Are the solutions equal? {torch.allclose(x_solve, x_inv)}")

# Print the performance comparison
print(f"Time taken using torch.linalg.solve: {time_solve:.6f} seconds")
print(f"Time taken using inverse and multiplication: {time_inv:.6f} seconds")

Are the solutions equal? True
Time taken using torch.linalg.solve: 0.012212 seconds
Time taken using inverse and multiplication: 0.016959 seconds


## Matrix Calculus

Next we should review some matrix calculus. This will help us when we discuss backpropagation next week!

We've discussed derivatives and how to take a derivative of a function with one variable. But in our deep nets, most functions will have multiple variables. So let's try to investigate how to take the derivative of those types of functions.

For example, suppose $a(x,y) = xy$ what is the derivative of $a(x,y)$. Depends on the if we are changing $x$ or $y$. Hence, we'll need to work with partial derivatives.

Suppose:

$$f(x,y) = 3x^2y$$

then 

$$ \nabla f(x,y) = \left[ \frac{\partial f (x,y)}{\partial x}, \frac{\partial f (x,y)}{\partial y} \right] = \left[6xy, 3x^2\right]$$

Let's take a second function: 


$$g(x,y) = 2x + y^8$$

then 

$$ \nabla g(x,y) = \left[ \frac{\partial g (x,y)}{\partial x}, \frac{\partial g (x,y)}{\partial y} \right] = \left[2, 8y^7\right]$$

As you can see, gradient functions organize their partial derivatives into a vector. We can extend this idea by stacking functions and organizing their gradients into a matrix: 

$$ J = \left[ \begin{array}{c} \nabla f(x,y) \\ \nabla g(x,y) \end{array} \right] = \left[ \begin{array}{cc} \frac{\partial f(x,y)}{\partial x} & \frac{\partial f(x,y)}{\partial y} \\ \frac{\partial g(x,y)}{\partial x} & \frac{\partial g(x,y)}{\partial y} \end{array} \right] = \left[ \begin{array}{cc} 6xy & 3x^2 \\ 2 & 8y^7 \end{array} \right] $$

The above is called the Jacobian matrix. 

### Definition of Jacobian matrix

For a function $ \mathbf{f}(\mathbf{x}) $, which takes a vector $ \mathbf{x} \in \mathbb{R}^n $ and produces a vector $ \mathbf{y} = \mathbf{f}(\mathbf{x}) \in \mathbb{R}^m $, the Jacobian matrix $ J $ is defined as the matrix of first-order partial derivatives of each component of $ \mathbf{f} $ with respect to each component of $ \mathbf{x} $.

If we have:

$$
\mathbf{f}(\mathbf{x}) = \begin{pmatrix} f_1(x_1, x_2, \dots, x_n) \\ f_2(x_1, x_2, \dots, x_n) \\ \vdots \\ f_m(x_1, x_2, \dots, x_n) \end{pmatrix}
$$

and

$$
\mathbf{x} = \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix}
$$

Then the Jacobian matrix $ J $ is an $ m \times n $ matrix where the element in the $ i $-th row and $ j $-th column is the partial derivative of the $ i $-th output function $ f_i $ with respect to the $ j $-th input $ x_j $:

$$
J = \begin{pmatrix} \frac{\partial f_1}{\partial x_1} & \frac{\partial f_1}{\partial x_2} & \dots & \frac{\partial f_1}{\partial x_n} \\ \frac{\partial f_2}{\partial x_1} & \frac{\partial f_2}{\partial x_2} & \dots & \frac{\partial f_2}{\partial x_n} \\ \vdots & \vdots & \ddots & \vdots \\ \frac{\partial f_m}{\partial x_1} & \frac{\partial f_m}{\partial x_2} & \dots & \frac{\partial f_m}{\partial x_n} \end{pmatrix}
$$

Quick note: This is called numerator layout. Depending on the paper/discpline, you can also see denominator layout which is the transpose of the above:

We can use PyTorch to calculate the Jacobian matrix as well. Let's get our 2D example from above again: 

$$ f_0(x_0,x_1) = 3x_0^2x_1 \; \; \; \; \; \; \; \; \; \; f_1(x_0,x_1) = 2x_0 + x_1^8 $$

and we saw that the Jacobian looked like: 

$$ J = \left[ \begin{array}{c} \nabla f_0(x_0,x_1) \\ \nabla f_1(x_0,x_1) \end{array} \right] = \left[ \begin{array}{cc} \frac{\partial f_0(x_0,x_1)}{\partial x_0} & \frac{\partial f_0(x_0,x_1)}{\partial x_1} \\ \frac{\partial f_1(x_0,x_1)}{\partial x_0} & \frac{\partial f_1(x_0,x_1)}{\partial x_1} \end{array} \right] = \left[ \begin{array}{cc} 6 x_0 x_1 & 3x_0^2 \\ 2 & 8x_1^7 \end{array} \right] $$

and at $\left[x_0, x_1\right] = \left[1, 1\right]$, we get: $J=\left[ \begin{array}{cc} 6 & 3 \\ 2 & 8 \end{array} \right]$ 


In [78]:
import torch

# def f0(x): 
#     return 3 * (x[0]**2) * x[1]
# def f1(x): 
#     return 2*x[0] + x[1]**8

def f(x): 
    return (3 * (x[0]**2) * x[1], 2*x[0] + x[1]**8)

x = torch.tensor([1, 1], dtype=float)
#print(f(x))
print(torch.autograd.functional.jacobian(f, x))

(tensor([6., 3.], dtype=torch.float64), tensor([2., 8.], dtype=torch.float64))


## Important Derivatives:

$$\frac{\partial A x}{\partial x} = A$$ (numerator format) 

Let $ A $ be a matrix of size $ m \times n $, and $ x $ be a vector of size $ n \times 1 $. The product $ A x $ is a vector of size $ m \times 1 $.

We want to compute the derivative of $ A x $ with respect to $ x $, i.e., $ \frac{\partial}{\partial x} (A x) $.

### Step 1: Understand the structure of the product

The matrix-vector product $ A x $ is a linear transformation. Each entry in the resulting vector is a linear combination of the components of the vector $ x $.

For instance, if we write the product element-wise:

$$
(A x)_i = \sum_{j=1}^{n} A_{ij} x_j
$$

where $ A_{ij} $ are the elements of the matrix $ A $ and $ x_j $ are the components of the vector $ x $.

### Step 2: Compute the derivative

To compute the derivative $ \frac{\partial}{\partial x} (A x) $, we need to examine how each component of $ A x $ changes with respect to each component of $ x $.

- The derivative of $ (A x)_i $ with respect to $ x_j $ is simply the matrix element $ A_{ij} $, because:

$$
(A x)_i = \sum_{j=1}^{n} A_{ij} x_j
$$

and the derivative of this with respect to $ x_j $ is $ A_{ij} $.



Note: if we're assuming denominator format, we would flip the indices

$$ \frac{\partial x^T x}{\partial x} = 2 x $$

Think of it this way, the product of a scalar and its transpose is scalar size:  

$$ x^T x = x_0^2 + x_1^2 + \ldots + x_n^2 = z(x) $$

so measuring the effect each $x_i$ value has on the end sum would yield a vector: 

$$ \left[ \frac{\partial z(x)}{\partial x_0}, \frac{\partial z(x)}{\partial x_1}, \ldots, \frac{\partial z(x)}{\partial x_n} \right] = \left[2 x_0, 2 x_1, \ldots 2 x_n\right] = 2x$$

## That's it for now

- Have a good weekend
- Remember your HW is due Monday evening
- Next week is on auto-differentiation fun